version: "0.1"
services:
  golang:
    build: "."
    dockerfile: ./docker_stuff/golang.dockerfile
    ports:
      - "8080:80"
    links:
      - db
  db:
    build: "."
    dockerfile: ./docker_stuff/postgres.dockerfile
    environment:
      - POSTGRES_PASSWORD=dnd
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dnd
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    links:
      - db