version: 2.0
jobs:
  GetCode:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: After check out
          command: |
            pwd
            ls -la
      - persist_to_workspace:
          root: /root/project
          paths:
            - .
  BuildJS:
    docker:
      - image: node:latest
    steps:
      - attach_workspace:
          at: /root/project
      - run:
          name: Building JS
          command: |
            cd ./ClientApp
            npm install
            npm run prod
  Deploy:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Deploying
          command: |
            apk add rsync
            echo $ssh_key > ~/.key
            rsync --filter=":- .gitignore" -e "ssh -i ~/.key" -avz ./ $ssh_login@$remote_host:$remote_path 

workflows:
  version: 2
  BaseWorkflow:
    jobs:
      - GetCode
      - BuildJS:
          requires:
            - GetCode
      - Deploy:
          requires:
            - BuildJS
