version: 2.0
jobs:
  GetCode:
    docker:
      - image: circleci/php:7.3.1-fpm-stretch-node
    steps:
      - checkout  
      - persist_to_workspace:
          root: .
          paths:
            - .
  BuildJS:
    docker:
      - image: circleci/php:7.3.1-fpm-stretch-node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Building JS
          command: |
            cd ./ClientApp
            npm install
            npm run prod
  Deploy:
    docker:
      - image: circleci/php:7.3.1-fpm-stretch-node
    steps:
      - run:
          name: Deploying
          command: |
            mkdir ~/.ssh
            echo "Host ilovek.bget.ru" >> ~/.ssh/config
            echo "  Username $ssh_login"
            echo "  IdentityFile $ssh_key"
            echo "  IdentitiesOnly yes"
            echo "  StrictHostKeyChecking no"
            rsync --filter=":- .gitignore" -avz ./ $ssh_login@$remote_host:$remote_path 

workflows:
  version: 2
  BaseWorkflow:
    jobs:
      - GetCode
      - BuildJS:
          requires:
            - GetCode
      - Deploy:
          requires:
            - BuildJS
