version: 2.0
jobs:
  GetCode:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: Checking out
          command: ls -la
  BuildJS:
    docker:
      - image: node:latest
    steps:
      - run:
          name: Building JS
          command: npm run prod
  Deploy:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Deploying
          command: |
            ls -la
            echo $ssh_key > ~/.key
            rsync --filter=":- .gitignore" -e "ssh -i ~/.key" -avz ./ $ssh_login@$remote_host:$remote_path 